### ISSUE TITLE
"Notes" is JSONObject or JSONArray?

### ISSUE THREAD

**Issue by Amitbhave** [razorpay/razorpay-java#48]
For some notifications, I get notes as jsonobject, while for some I get jsonarray.
Can someone clarify when notes will be jsonobject and when it will be jsonarray? @captn3m0  @ankit-rzp

**Comment by jitendra-1217** [comment]
@Amitbhave : It would be JSON Object.

Request you to share more details on when you got different data types for notes attribute, e.g. the resource/payment id etc.

One reason that I can think of when it could be JSON Array is - old version entities have notes as list data type i.e. ["value1", "value2"] etc instead of {"key1":"value1", "key2":"value2"} and in former case the response would be getting parsed as JSON Array. But this should not happen now.

**Comment by Amitbhave** [comment]
Hi @jitendra-1217 , 1st time it was invoice.paid when I had got notes as jsonobject in payment entity in requestbody; whereas for payment.captured, i had got notes as jsonarray in requestbody.
(I am talking about webhooks here)

So it should be jsonobject in all cases now? Can you please verify from your side for webhooks, all events you are sending notes as jsonobject?

**Comment by harman28** [comment]
@Amitbhave Sorry for the late response, noting a response here anyway for anyone else who comes looking.

Yes, `notes` is always a JSON object, in webhooks as well as API responses.
